### ISSUE TITLE
Secuity issue: asyncpg errors are sent to discord

### ISSUE THREAD

**Issue by AnotherZane** [Voxel-Fox-Ltd/Flower#15]
When the bot fails to connect to the database, the connection refused error is sent to discord. This error message includes the ip of the server and the port on which the database is hosted at. The ip is currently localhost but this could potentially leak a new database host ip in the future. I highly suggest sending a generic error message instead - with specific error codes so you can still debug as to what went wrong.

![An example of the current behaviour](https://cdn.fakezane.net/HOyUf.png)

**Comment by ethanbreck** [comment]
The IP address is Localhost, but the issue seems to be the Docker container for the flower bot, is having issues talking to the Redis server they have managing the data for each user's plants.

**Comment by 4Kaylum** [comment]
The IP is localhost and the port is Postgres default. I have my Postgres configured to whitelist IPs so it can't be accessed externally. 

This isn't really a security issue as much as it is just me being lazy with error messages.

**Comment by 4Kaylum** [comment]
> the issue seems to be the Docker container for the flower bot, is having issues talking to the Redis server they have managing the data for each user's plants.

The issue was actually much stupider: the bot's log files filled the disk because I didn't set up log rotation properly. Whoops.

**Comment by ethanbreck** [comment]
Ah, yeah. That would cause it, Ive made the same error on some of things
