### ISSUE TITLE
Add a Yucca plant (or other dry climate plants)

### ISSUE THREAD

**Issue by WireSplitter** [Voxel-Fox-Ltd/Flower#26]
This is really just a small suggestion, but could you add a Yucca plant? I find them pretty neat and have one. 

If you'd like to add a little complication, Yuccas and other dry climate plants need watering less often, so they could have a longer wait for watering (so that they don't get over-watered) but also have a longer life if left un-watered.

Whether or not you add this suggestion, I've been having a lot of fun with the flower bot, and thank you for making it!

**Comment by 4Kaylum** [comment]
I don't have a system in place for having plants with variable length water times - that's a neat idea. As for the plant itself, I can add it to the list of plants that I might commission in future, but until then you're welcome to draw the art pieces yourself if you want it in. `p.volunteer` gives you the information you need.

I'm glad you're having fun with the bot! c:
