### ISSUE TITLE
Fix herbiary gifs

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/Flower#38]

**Comment by g-thome** [comment]
what's the problem exactly?

**Comment by 4Kaylum** [comment]
I don't know how to use PIL well enough to properly add the transparency to the GIFs. As such they display as black at the moment. 

I'd also like to offset them so the pot is always at the bottom of the image, but the transparency is my main concern.

**Comment by 4Kaylum** [comment]
Done.
