### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by Kore-Development** [Voxel-Fox-Ltd/Flower#44]
I'm trying to make a fork, but I don't know how to run the bot. I don't know much about discord.py.

**Comment by JMcB17** [comment]
Do you know how to install dependencies with pip?

This uses voxelbotutils, https://github.com/Voxel-Fox-Ltd/VoxelBotUtils, you need to run it using that.

**Comment by g-thome** [comment]
i think it would help to have a quick guide on how to run it locally described in the readme

**Comment by 4Kaylum** [comment]
I may make a separate file for it (maybe one to include by default with VBU?) but I don't want to add that information to the README as I'm trying to keep that as a sort of "marketing" spiel. 

The person who opened the issue hasn't commented in several days so I'm closing this.
