### ISSUE TITLE
Out-of-date README

### ISSUE THREAD

**Issue by VerifiedGruber** [Voxel-Fox-Ltd/Flower#6]
## Main findings:
- The README seems out-of-date regarding both `botutils-rewrite` and `master` branches codes and bots responses.

## Main Analysis
- The lack of README updates really confuses people, if it should act as a shorter documentation process, it'd be advised to be always kept up-to-date in order to avoid this kind of simple but avoidable lack of trust in a project's documentation files.

## Main solution
- If the README file not meant to be constantly updated it is recommended to move every aspect of documentation to a proper documentation sharing tool or service and only hyperlink it on the README file.

**Comment by 4Kaylum** [comment]
The readme for this isn't meant to act as documentation, but rather an entry point for the bot itself (which is a valid use case for a readme). Being an actually running bot, all commands are listed within the bot's help command, as is the case with every other bot. 

This repo has no in-depth documentation for the program itself, which would be a separate issue to the one described here.

**Comment by VerifiedGruber** [comment]
> The readme for this isn't meant to act as documentation, but rather an entry point for the bot itself (which is a valid use case for a readme). Being an actually running bot, all commands are listed within the bot's help command, as is the case with every other bot.
> 
> This repo has no in-depth documentation for the program itself, which would be a separate issue to the one described here.
> 
> You've described both the issue and your proposed solution in very vague terms; could you elaborate more on what you mean?

That's a fair point. My proposed solution would be to implement a software like Sphinx in order to auto-generate a proper documentation regarding both the bot itself and the software generated by its services on Discord servers. This way you could make a documentation easily within the source itself without having to worry with organizing a Wiki of sorts manually, there are both services and open-source software capable of generating that for free.

**Comment by 4Kaylum** [comment]
I see what you're going for; Sphinx wouldn't really serve a purpose in this case as this is a whole project rather than a collection of tools. I use Sphinx in a couple of other projects that I've used and I don't think it would be great for this.

I'm also thinking of changing how the bot works as a whole, so making a wiki may not be the best of ideas for now either :/

**Comment by VerifiedGruber** [comment]
That's understandable. I'll close the issue then since it doesn't seem to be a useful suggestion as of right now and there are changes underway that would require constantly editing in a way that maybe it's not the best use of your time. I'll re-open the issue or create a PR to help document the bot if the opportunity arises, thank you @4Kaylum.
